[package]
name = "go2hpo_genetic_algorithm"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
lazy_static = "1.5.0"
ontolius = "0.5.0"
rand = "0.9.0"


[dev-dependencies]
flate2 = "1.1.0"
